import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "../_components/ui/sidebar";
import { AppSidebar } from "./_components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="min-w-0 flex-1">
        <header className="flex h-16 items-center justify-between border-b px-4">
          <div className="flex items-center gap-3">
            <SidebarTrigger />
          </div>

          <div className="flex items-center gap-3">
            <span className="hidden text-sm font-medium sm:inline">
              Administrador
            </span>
            <div
              role="img"
              aria-label="Avatar do administrador"
              className="flex size-9 items-center justify-center rounded-full bg-green-100 text-sm font-semibold text-green-700"
            >
              AD
            </div>
          </div>
        </header>

        <div className="p-4">{children}</div>
      </main>
    </SidebarProvider>
  );
}
