import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "../_components/ui/sidebar";
import { AppSidebar } from "./_components/app-sidebar";
import Image from "next/image";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <Toaster />
      <main className="bg-primary/5 min-w-0 flex-1">
        <header className="flex h-16 items-center justify-between border-b px-4">
          <div className="flex items-center gap-3">
            <SidebarTrigger />
          </div>

          <div className="flex items-center gap-3">
            <span className="hidden text-sm font-medium sm:inline">
              Administrador
            </span>
            <div
              role="img"
              aria-label="Avatar do administrador"
              className="flex size-9 items-center justify-center rounded-full bg-green-100 text-sm font-semibold text-green-700"
            >
              AD
            </div>
          </div>
        </header>

        <div className="relative isolate overflow-hidden p-4">
          <Image
            src="/folha.png"
            alt=""
            aria-hidden="true"
            fill
            className="z-0 scale-[0.7] object-contain opacity-[0.05]"
          />

          <div className="relative z-10">{children}</div>
        </div>
      </main>
    </SidebarProvider>
  );
}
